### ISSUE TITLE
Design and build  the database

### ISSUE THREAD

**Issue by ghassanmas** [nervnews/nerv#10]
- Design the Database Scheme, how much tables do we really need, what columns should be in the table.

- Write a SQL file that once run it will create all the needed tables 

- Write basic Function/query like add user, get user interests...etc

**Comment by harrygfox** [comment]
How is the progress of this issue @ghassanmas? Could you add a time estimate if it still needs to be done?

**Comment by ghassanmas** [comment]
I will start working on this right now
