### ISSUE TITLE
"Visualize button" on article listing

### ISSUE THREAD

**Issue by MynahMarie** [nervnews/nerv#11]
As a user,
I want to see a button on an article listing to take me to the sentiment analysis page
So that I know how to visualise the sentiment of the article

User acceptance criteria:
- [x] A "Visualize" clickable button under the article that directs to another page in the app.
Related to #12 (Display sentiment analysis)

**Comment by MynahMarie** [comment]
Created a visualize button on the home page under each article.

**Comment by harrygfox** [comment]
This is done!
Sentiment analysis is in the console and will be displayed as part of #12
