### ISSUE TITLE
Display sentiment analysis

### ISSUE THREAD

**Issue by MynahMarie** [nervnews/nerv#12]
As a user
I want to have a visual representation of the sentiment analysis for this article in the form of a bubble graph
So that it is easy to have a general impression of the sentiment of an article in a fast and convenient way.

User acceptance criteria:
- [ ] Perform sentiment analysis on an article
- [ ] A graph that shows negative and positive sentiments

**Comment by harrygfox** [comment]
Please can we add a time estimate to this issue?

**Comment by sophieeejw** [comment]
data = [
  {
    word: "house",
    freq: 8,
    sentiment: "neutral",
    size: 8,
    color_score: 0
  },
  {
    word: "subpoena",
    freq: 3,
    sentiment: "negative",
    size: 8,
    color_score: -1
  },
  {
    word: "white",
    freq: 7,
    sentiment: "neutral",
    size: 7,
    color_score: 0
  },
  {
    word: "refused",
    freq: 2,
    sentiment: "negative",
    size: 7,
    color_score: -1
  },
  {
    word: "gag",
    freq: 1,
    sentiment: "negative",
    size: 6,
    color_score: -1
  },
  {
    word: "condemned",
    freq: 1,
    sentiment: "negative",
    size: 6,
    color_score: -1
  },
  {
    word: "refuse",
    freq: 1,
    sentiment: "negative",
    size: 6,
    color_score: -1
  },
  {
    word: "grand",
    freq: 1,
    sentiment: "positive",
    size: 6,
    color_score: 1
  },
  {
    word: "committee",
    freq: 5,
    sentiment: "neutral",
    size: 5,
    color_score: 0
  },
  {
    word: "bannon",
    freq: 5,
    sentiment: "neutral",
    size: 5,
    color_score: 0
  }
];
