### ISSUE TITLE
os module?

### ISSUE THREAD

**Issue by Karyum** [nervnews/nerv#23]
https://github.com/nervnews/nerv/blob/master/src/server.js#L4

there is no such thing in your package.json and you afre not using it anywhere, so make a pull request just to delete it

( @ghassanmas yes mate a 1 line pull request )

**Comment by ghassanmas** [comment]
We may need it soon

**Comment by Karyum** [comment]
untill then you can delete it

**Comment by claireinez** [comment]
I agree with @Karyum. You should only install a dependency when it is actually needed in the project (or at least don't add it into source control when it is not yet being used).

**Comment by harrygfox** [comment]
Has this been resolved @ghassanmas?

**Comment by ghassanmas** [comment]
Yes

**Comment by Karyum** [comment]
can you reference the pull request that this was resolved in ?

**Comment by ghassanmas** [comment]
https://github.com/nervnews/nerv/commit/856de38aa61b534f8840d20daf60e62a94a74738

**Comment by Karyum** [comment]
https://github.com/nervnews/nerv/pull/26/commits/ab76abaa305f486b2656a45716bc34ee6d11b983
