### ISSUE TITLE
Filtering the guardian API Results

### ISSUE THREAD

**Issue by ghassanmas** [nervnews/nerv#25]
Write a function that takes response of the guardian API then filter the results to keep only what we need. 
Also Make the guardian API get the full results.
Relates #19

**Comment by harrygfox** [comment]
@ghassanmas is this a stage 2 or stage 2 feature?

**Comment by ghassanmas** [comment]
This a stage 1 feature, this will helps to have one standard form of the articles data we get.

**Comment by harrygfox** [comment]
This feature has been implemented, can we confirm that it's been tested and is done, @nervnews/developers? IF so then Let's close this issue

**Comment by ghassanmas** [comment]
@harrygfox tested and fixed
