### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by MynahMarie** [nervnews/nerv#3]
We should research and find the APIs we wish to query in order to get back a list of article. Maybe we can start with 1 API and build from there.

Related to https://github.com/nervnews/nerv/issues/5

**Comment by harrygfox** [comment]
@MynahMarie [The Guardian](http://open-platform.theguardian.com/) is open source, might be a nice place to start?

**Comment by MynahMarie** [comment]
@harrygfox will definitely check out Guardian, for the meantime I would like to suggest maybe this API: 
https://newsapi.org
It's free for developers to use and has access to 5,000 news sources. It's also possible to search by keyword. 

What does everyone think?

**Comment by MynahMarie** [comment]
Ok, so I guess we will stick to Guardian as Pavel suggested because it is true that it can return a full article and we need text in order to analyze the data.
