### ISSUE TITLE
User Journey - Data Visualization

### ISSUE THREAD

**Issue by MynahMarie** [nervnews/nerv#9]
- [x] Once on the article list page, each article has a button that directs the user to a data visualization page. #11 
- [ ]  The sentiment analysis for that article is represented in the form of a bubble graph. #12

**Comment by harrygfox** [comment]
Do we have designs for this @MynahMarie?

**Comment by MynahMarie** [comment]
@harrygfox We have only a very basic idea which we showed in the prototype. We are still unsure of how would be the most efficient and visually pleasant way to integrate this feature...

**Comment by harrygfox** [comment]
Following our standup this morning, this will be one the focuses of today's work. 
Could we add a time estimate to this @nervnews/developers?

If not for the total feature then at least for the research spike.

**Comment by harrygfox** [comment]
Closing in favour of #12
